name: MacOS Build

on:
  workflow_call:
    inputs:
      workspace_file:
        description: The name of the workspace file.
        type: string
        required: true

env: {}

defaults:
  run:
    working-directory: cocoa

jobs:
  build-12:
    name: Build MacOS 12
    runs-on: macos-12
    strategy:
      matrix:
#        architecture:
#          - ppc
#          - ppc64
#          - i386
#          - x86_64
#          - arm
#          - arm64
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -workspace ${{ inputs.workspace_file }} -scheme WingsSaver -configuration=${{ matrix.configuration }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/
  build-13:
    name: Build MacOS 13
    runs-on: macos-13
    strategy:
      matrix:
#        architecture:
#          - ppc
#          - ppc64
#          - i386
#          - x86_64
#          - arm
#          - arm64
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -workspace ${{ inputs.workspace_file }} -scheme WingsSaver -configuration=${{ matrix.configuration }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/
  build-13:
    name: Build MacOS 14
    runs-on: macos-14
    strategy:
      matrix:
#        architecture:
#          - ppc
#          - ppc64
#          - i386
#          - x86_64
#          - arm
#          - arm64
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -workspace ${{ inputs.workspace_file }} -scheme WingsSaver -configuration=${{ matrix.configuration }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/
  build-13:
    name: Build MacOS 15
    runs-on: macos-15
    strategy:
      matrix:
#        architecture:
#          - ppc
#          - ppc64
#          - i386
#          - x86_64
#          - arm
#          - arm64
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -workspace ${{ inputs.workspace_file }} -scheme WingsSaver -configuration=${{ matrix.configuration }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/